version: '2'
services:
   app:
       container_name: app
       image: php:7.2-apache
       volumes:
           - "./app/code/:/var/www/html/"
           - "./app/logs/:/var/log/apache2/"
       ports:
           - "80:80"
           - "443:443"
       tty: true
       restart: always
       networks:
         lampnetwork:
            ipv4_address: 192.168.0.2         


   mysql:
       image: mysql:5.7
       container_name: mysql
       volumes:
           - "./mysql/db/:/var/lib/mysql/"
           - "./mysql/conf/my.cnf:/etc/mysql/my.cnf"
       environment:
           - MYSQL_ROOT_PASSWORD=adm1n
           - MYSQL_USER=adm1n
           - MYSQL_PASSWORD=adm1n
       ports:
           - "3306"             
       restart: always
       networks:
         lampnetwork:
            ipv4_address: 192.168.0.100

   memcached:
       image: memcached
       container_name: memcached
       ports:
           - 11211:11211
       restart: always
       networks:
         lampnetwork:
            ipv4_address: 192.168.0.6

networks:
  lampnetwork:
    driver: bridge
    ipam:
     config:
       - subnet: 192.168.0.0/16
         gateway: 192.168.0.1
